language: go
sudo: false
go:
- 1.10.x
- 1.9.x
- 1.8.x
services:
  - docker
install:
- docker run -d --name nats -p 4222:4222 -p 6222:6222 -p 8222:8222 nats
- docker run -d --name redis -p6379:6379 redis
- go get -t ./...
- go get github.com/mattn/goveralls
- go get -u honnef.co/go/tools/cmd/megacheck
- go get -u github.com/client9/misspell/cmd/misspell
before_script:
- $(exit $(go fmt ./... | wc -l))
- go vet ./...
- misspell -error -locale US .
- megacheck -ignore "$(cat staticcheck.ignore)" ./...
script:
- go test -i -race ./...
- if [[ "$TRAVIS_GO_VERSION" == 1.9.* ]]; then ./.scripts/cover.sh; else go test -v -race ./...; fi